// Applies the embedded SQL migrations (generated by `pnpm db:migrate:new`) without the Prisma CLI.
// Each migration runs in its own transaction (DDL is transactional in both SQLite and PostgreSQL), so a
// failure rolls back cleanly. For SQLite an on-disk snapshot is taken before any pending migration runs.
import fs from "node:fs";
import path from "node:path";
import { openSqlite, type DatabaseSync } from "./adapter-node-sqlite";
import { POSTGRES_MIGRATIONS, SQLITE_MIGRATIONS, type EmbeddedMigration } from "./migrations.generated";

export type Provider = "sqlite" | "postgres";

export interface MigrateResult {
  applied: string[];
  schemaVersion: string;
  preMigrationBackup: string | null;
  fresh: boolean;
}

const TABLE = "_petra_migrations";

export function latestSchemaVersion(provider: Provider = "sqlite"): string {
  const list = provider === "sqlite" ? SQLITE_MIGRATIONS : POSTGRES_MIGRATIONS;
  return list.at(-1)?.id ?? "";
}

export async function migrate(opts: { provider: Provider; sqliteFile?: string; databaseUrl?: string; backupDir?: string }): Promise<MigrateResult> {
  return opts.provider === "sqlite" ? migrateSqlite(opts.sqliteFile!, opts.backupDir) : migratePostgres(opts.databaseUrl!);
}

function stamp() {
  return new Date().toISOString().replace(/\D/g, "").slice(0, 14);
}

/** Schema version recorded in a SQLite file (used to validate backups before restore). */
export function sqliteSchemaVersion(file: string): string | null {
  const db = openSqlite(file, { readOnly: true });
  try {
    const t = db.prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name=?`).get(TABLE);
    if (!t) return null;
    const r = db.prepare(`SELECT id FROM ${TABLE} ORDER BY id DESC LIMIT 1`).get() as { id: string } | undefined;
    return r?.id ?? null;
  } finally {
    db.close();
  }
}

function migrateSqlite(file: string, backupDir?: string): MigrateResult {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const db = openSqlite(file);
  try {
    db.exec(`CREATE TABLE IF NOT EXISTS ${TABLE} (id TEXT PRIMARY KEY, applied_at TEXT NOT NULL)`);
    const done = new Set((db.prepare(`SELECT id FROM ${TABLE}`).all() as { id: string }[]).map((r) => r.id));
    const pending = SQLITE_MIGRATIONS.filter((m) => !done.has(m.id));
    const fresh = done.size === 0;
    const known = new Set(SQLITE_MIGRATIONS.map((m) => m.id));
    const unknown = [...done].filter((id) => !known.has(id));
    if (unknown.length) throw new Error(`This database was created by a newer PetraPMS version (migration ${unknown.at(-1)}). Install the latest version.`);
    let backup: string | null = null;
    if (pending.length && !fresh && backupDir) {
      fs.mkdirSync(backupDir, { recursive: true });
      backup = path.join(backupDir, `petrapms-pre-migration-${stamp()}.db`);
      db.exec(`VACUUM INTO '${backup.replace(/'/g, "''")}'`);
    }
    for (const m of pending) applySqlite(db, m);
    return { applied: pending.map((m) => m.id), schemaVersion: latestSchemaVersion("sqlite"), preMigrationBackup: backup, fresh };
  } finally {
    db.close();
  }
}

function applySqlite(db: DatabaseSync, m: EmbeddedMigration) {
  db.exec("PRAGMA foreign_keys=OFF");
  db.exec("BEGIN IMMEDIATE");
  try {
    db.exec(m.sql);
    db.prepare(`INSERT INTO ${TABLE}(id, applied_at) VALUES(?, ?)`).run(m.id, new Date().toISOString());
    const fk = db.prepare("PRAGMA foreign_key_check").all();
    if (fk.length) throw new Error(`Migration ${m.id} left ${fk.length} foreign key violation(s)`);
    db.exec("COMMIT");
  } catch (e) {
    try {
      db.exec("ROLLBACK");
    } catch {
      /* already rolled back */
    }
    throw new Error(`Migration ${m.id} failed and was rolled back: ${(e as Error).message}`);
  } finally {
    db.exec("PRAGMA foreign_keys=ON");
  }
}

async function migratePostgres(url: string): Promise<MigrateResult> {
  const { Client } = await import("pg");
  const client = new Client({ connectionString: url });
  await client.connect();
  try {
    // serialise concurrent app instances starting at the same time
    await client.query("SELECT pg_advisory_lock(727301)");
    await client.query(`CREATE TABLE IF NOT EXISTS ${TABLE} (id TEXT PRIMARY KEY, applied_at TEXT NOT NULL)`);
    const done = new Set((await client.query(`SELECT id FROM ${TABLE}`)).rows.map((r: { id: string }) => r.id));
    const known = new Set(POSTGRES_MIGRATIONS.map((m) => m.id));
    const unknown = [...done].filter((id) => !known.has(id));
    if (unknown.length) throw new Error(`This database was created by a newer PetraPMS version (migration ${unknown.at(-1)}).`);
    const pending = POSTGRES_MIGRATIONS.filter((m) => !done.has(m.id));
    for (const m of pending) {
      await client.query("BEGIN");
      try {
        await client.query(m.sql);
        await client.query(`INSERT INTO ${TABLE}(id, applied_at) VALUES($1, $2)`, [m.id, new Date().toISOString()]);
        await client.query("COMMIT");
      } catch (e) {
        await client.query("ROLLBACK");
        throw new Error(`Migration ${m.id} failed and was rolled back: ${(e as Error).message}`);
      }
    }
    return { applied: pending.map((m) => m.id), schemaVersion: latestSchemaVersion("postgres"), preMigrationBackup: null, fresh: done.size === 0 };
  } finally {
    await client.query("SELECT pg_advisory_unlock(727301)").catch(() => undefined);
    await client.end();
  }
}
